apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ops-config
  namespace: kubernetes-operations-dashboard
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "k8s-ops-jaeger:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_SERVICE_NAME: "kubelens-backend"
  OTEL_TRACES_SAMPLE_RATIO: "1"
