apiVersion: v1
kind: Service
metadata:
  name: k8s-ops-grafana
  namespace: kubernetes-operations-dashboard
  labels:
    app.kubernetes.io/name: k8s-ops-grafana
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: k8s-ops-grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
