apiVersion: v1
kind: Service
metadata:
  name: k8s-ops-prometheus
  namespace: kubernetes-operations-dashboard
  labels:
    app.kubernetes.io/name: k8s-ops-prometheus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: k8s-ops-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
