apiVersion: v1
kind: Service
metadata:
  name: k8s-ops-predictor
  namespace: kubernetes-operations-dashboard
  labels:
    app.kubernetes.io/name: k8s-ops-predictor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: k8s-ops-predictor
  ports:
    - name: http
      port: 8001
      targetPort: http
