{{- if .Values.predictor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubelens.fullname" . }}-predictor
  labels:
    {{- include "kubelens.labels" . | nindent 4 }}
    app.kubernetes.io/component: predictor
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.predictor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubelens.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: predictor
{{- end }}
