apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelens-dashboard
  namespace: kubernetes-operations-dashboard
  labels:
    app.kubernetes.io/name: kubernetes-operations-dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelens-predictor
  namespace: kubernetes-operations-dashboard
  labels:
    app.kubernetes.io/name: k8s-ops-predictor
